version: "3.7"

services:
  client:
    container_name: client
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3030:3000
    networks:
      - default
    restart: unless-stopped
    volumes:
      - ./client:/service

  api:
    container_name: api
    image: node:latest
    ports:
      - 4000:4000
    networks:
      - default
    depends_on:
      - db
    restart: always
    volumes:
      - ./api:/usr/local/app
    working_dir: /usr/local/app
    entrypoint: "/bin/bash"
    command: '-c "if [ ! -d "node_modules" ]; then npm i; fi; npm start"'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: 5432
      DATABASE_HOST: db

  db:
    container_name: postgres
    image: postgres
    restart: always
    networks:
      - default
    ports:
      - 5433:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PGDATA: /var/lib/postgresql/data

networks:
  default:
