version: "3.7"

services:
  api:
    image: node:latest
    ports:
      - 4000:4000
    depends_on:
      - db
    restart: always
    volumes:
      - ./api:/usr/local/app
    working_dir: /usr/local/app
    entrypoint: "/bin/bash"
    command: '-c "if [ ! -d "node_modules" ]; then npm i; fi; npm start"'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: 5432
      DATABASE_HOST: db

  db:
    image: postgres
    restart: always
    networks:
      - default
    ports:
      - 5433:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PGDATA: /var/lib/postgresql/data
