[build]
  command = "yarn build"
  functions = "functions" # not strictly required but putting this for convenience
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200